# Generated by Django 5.0.6 on 2024-05-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productimage_thumbnail_alter_productimage_file_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='file_path',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
